server:
  port: 9001

spring:
  application:
    name: cloudbase-defaultserver
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://localhost:9411
#    enabled: true
#    locator:
#      discovery:
#        enabled: true