server:
  port: 9080

spring:
  application:
    name: cloudbase-gateway
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  zipkin:
    base-url: http://localhost:9411
#    enabled: true
#    locator:
#      discovery:
#        enabled: true

logging:
  level:
    root: INFO
    com.huang: DEBUG
    org.springframework: INFO
    org.springframework.cloud.gateway: INFO